server:
  port: 48585

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: test-service-route
              uri: lb://test-service
              predicates:
                - Path=/api/test/**
              filters:
                - PreserveHostHeader
#                - StripPrefix=1
            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**,/api/file/**
              filters:
                - PreserveHostHeader

            - id: collect-analyze-service-route
              uri: lb://collect-analyze-service
              predicates:
                - Path=/api/**
              filters:
                - PreserveHostHeader

  config:
    import: nacos:gateway.yaml