server:
  port: 46552

spring:
  application:
    name: compare-rank-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml

  config:
    import: nacos:compare-rank-service.yaml

management:
  endpoints:
    web:
      exposure:
        include: '*'

emqx:
  url: tcp://localhost:41883
  client-id: compare-rank-service
  topics: energy/device/+/data
  qos: 1
  clean-session: false