server:
  port: 46540

spring:
  application:
    name: test-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml

  config:
    import: nacos:test-service.yaml

management:
  endpoints:
    web:
      exposure:
        include: '*'

test:
  testStr:
    TEST